apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-uoiz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0068-tenant/tkrw-pr712-0075-0068-app/devfile-sample-uoiz@sha256:d9aa7e51dff11dbb084cc7cb80aeb8f49d1ad2dc78d4d36549d7216e14f132ba
        name: my-nodejs
        resources: {}
status: {}
